name: infinite_scroll_pagination
description: Lazily load and display pages of items as the user scrolls down your screen.
# version: 3.2.0
homepage: https://github.com/EdsonBueno/infinite_scroll_pagination

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=3.10.5"

dependencies:
  flutter:
    sdk: flutter
  sliver_tools:
    git:
      url: https://github.com/vlado-rudenok/sliver_tools.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.9
  test: ^1.16.5
